//! Tauri 2 plugin build script.
//!
//! Lists every command exposed by `polybase-tauri` so the `tauri_plugin` build helper can
//! auto-generate the `permissions/autogenerated/commands/<cmd>.toml` files (one `allow-<cmd>`
//! and one `deny-<cmd>` permission per entry). The aggregate `default` permission set lives
//! in `permissions/default.toml` and references those autogenerated entries.
//!
//! To add a new command:
//!   1. Implement it in `src/commands.rs` (with `#[tauri::command]`).
//!   2. Add it to the `tauri::generate_handler!` list in `src/lib.rs`.
//!   3. Add its bare name to `COMMANDS` below.
//!   4. Add `"allow-<cmd>"` to `permissions/default.toml` so it lands in the default set.

const COMMANDS: &[&str] = &[
    "configure",
    "set_session",
    "clear_session",
    "current_session",
    "edge_call",
    "encrypt",
    "decrypt",
    "encrypt_batch",
    "decrypt_batch",
    "kvs_get",
    "kvs_set",
    "kvs_delete",
    "storage_upload",
    "storage_download",
    "storage_delete",
    "storage_list",
    "storage_signed_url",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
